// Generated by tools/generate_assets.py. Do not edit by hand.
//
// Derived from pimoroni/pimoroni-pico (MIT, Copyright (c) 2021 Pimoroni Ltd).

#pragma once

#include "hardware/pio.h"

static const uint16_t galactic_unicorn_program_instructions[] = {
    0x6048, 0x6008, 0x7121, 0xE004, 0x0026, 0xE005, 0xBA42, 0x7121,
    0xE004, 0x002B, 0xE005, 0xBA42, 0x7121, 0xE004, 0x0030, 0xE005,
    0x7A65, 0x0082, 0x6068, 0xE506, 0xE000, 0x6040, 0x0096, 0xE004,
};

static const struct pio_program galactic_unicorn_program = {
    .instructions = galactic_unicorn_program_instructions,
    .length = 24,
    .origin = -1,
};

static inline pio_sm_config galactic_unicorn_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + 0, offset + 23);
  // ".side_set 1 opt" means a 2-bit sideset field, optional, not pindirs.
  sm_config_set_sideset(&c, 2, true, false);
  return c;
}
