#!/usr/bin/env python3
"""Regenerate the gamma table and PIO program headers.

The gamma curve and the PIO program both originate in pimoroni/pimoroni-pico
(MIT, Copyright (c) 2021 Pimoroni Ltd). The gamma table is reproduced by
formula rather than copied; tests/test_assets.py proves the result is
identical to the upstream table.
"""
from pathlib import Path

import adafruit_pioasm

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "components" / "galactic_unicorn"

BANNER = """// Generated by tools/generate_assets.py. Do not edit by hand.
//
// Derived from pimoroni/pimoroni-pico (MIT, Copyright (c) 2021 Pimoroni Ltd).
"""


def write_gamma():
    values = [round(pow(i / 255, 2.2) * 16383) for i in range(256)]
    rows = []
    for i in range(0, 256, 16):
        rows.append("    " + ", ".join(str(v) for v in values[i:i + 16]) + ",")
    body = "\n".join(rows)
    (OUT / "gu_gamma.h").write_text(
        f"""{BANNER}
#pragma once

#include <cstdint>

// 14-bit gamma correction, curve exponent 2.2, output range 0 to 16383.
static const uint16_t GALACTIC_UNICORN_GAMMA_14BIT[256] = {{
{body}
}};
"""
    )


def write_pio():
    program = adafruit_pioasm.Program((ROOT / "tools" / "galactic_unicorn.pio").read_text())
    words = list(program.assembled)
    kwargs = program.pio_kwargs
    assert kwargs["sideset_pin_count"] == 1 and kwargs["sideset_enable"] is True
    wrap, wrap_target = kwargs["wrap"], kwargs["wrap_target"]

    rows = []
    for i in range(0, len(words), 8):
        rows.append("    " + ", ".join(f"0x{w:04X}" for w in words[i:i + 8]) + ",")
    body = "\n".join(rows)

    (OUT / "gu_pio.h").write_text(
        f"""{BANNER}
#pragma once

#include "hardware/pio.h"

static const uint16_t galactic_unicorn_program_instructions[] = {{
{body}
}};

static const struct pio_program galactic_unicorn_program = {{
    .instructions = galactic_unicorn_program_instructions,
    .length = {len(words)},
    .origin = -1,
}};

static inline pio_sm_config galactic_unicorn_program_get_default_config(uint offset) {{
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + {wrap_target}, offset + {wrap});
  // ".side_set 1 opt" means a 2-bit sideset field, optional, not pindirs.
  sm_config_set_sideset(&c, 2, true, false);
  return c;
}}
"""
    )


if __name__ == "__main__":
    write_gamma()
    write_pio()
    print(f"wrote {OUT / 'gu_gamma.h'} and {OUT / 'gu_pio.h'}")
